const express = require("express");
const controller = require("../controller/auth.controller");
const { auth, authorize } = require("../middleware/auth.middleware");
const router = express.Router();
router.post("/login", controller.login);
router.post("/register/customer", controller.registerCustomer);
router.post("/refresh-token", controller.refreshToken);
router.post("/logout", controller.logout);
router.post("/logout-all", auth, controller.logoutAll);
router.post("/change-password", auth, controller.changePassword);
router.post("/unlock-account", auth, authorize("admin"), controller.unlockAccount);
module.exports = router;
