const express = require("express");
const c = require("../controller/backup.controller");
const { auth, authorize } = require("../middleware/auth.middleware");
const r = express.Router();
r.use(auth, authorize("admin"));
r.get("/", c.list);
r.post("/", c.create);
r.get("/history", c.history);
r.get("/settings", c.settings);
r.put("/settings", c.saveSettings);
r.post("/retention", c.retention);
r.get("/:id", c.get);
r.post("/:id/restore", c.restore);
module.exports = r;
