const authRouter = require("./auth.router");
const userRouter = require("./user.router");
const customerRouter = require("./customer.router");
const vehicleRouter = require("./vehicle.router");
const accessoryRouter = require("./accessory.router");
const orderRouter = require("./order.router");
const contractRouter = require("./contract.router");
const inspectionRouter = require("./inspection.router");
const deviceRouter = require("./device.router");
const sessionRouter = require("./session.router");
const auditLogRouter = require("./auditLog.router");
const securityLevelRouter = require("./securityLevel.router");
const backupRouter = require("./backup.router");
const monitoringRouter = require("./monitoring.router");
const employeeRouter = require("./employee.router");
module.exports = (app) => {
  app.use("/api/auth", authRouter);
  app.use("/api/users", userRouter);
  app.use("/api/customers", customerRouter);
  app.use("/api/vehicles", vehicleRouter);
  app.use("/api/accessories", accessoryRouter);
  app.use("/api/orders", orderRouter);
  app.use("/api/contracts", contractRouter);
  app.use("/api/inspections", inspectionRouter);
  app.use("/api/devices", deviceRouter);
  app.use("/api/sessions", sessionRouter);
  app.use("/api/audit-logs", auditLogRouter);
  app.use("/api/security-levels", securityLevelRouter);
  app.use("/api/backups", backupRouter);
  app.use("/api/monitoring", monitoringRouter);
  app.use("/api/employees", employeeRouter);
};
