import { useCallback, useEffect, useState } from 'react';
import { Alert, Image, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { SafeAreaView } from 'react-native-safe-area-context';
import { confirmContract, getContractById } from '../../api/contract.api';
import PrimaryButton from '../../components/common/PrimaryButton';
import StatusBadge from '../../components/contract/StatusBadge';
import { formatVND } from '../../utils/format';
import { COLORS, SHADOW } from '../../utils/theme';

const Row = ({ label, value }) => <View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{value || '—'}</Text></View>;
export default function ContractDetailScreen({ navigation, route }) {
  const [contract, setContract] = useState(null); const [loading, setLoading] = useState(true); const [confirming, setConfirming] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { try { setError(''); setContract(await getContractById(route.params.contractId)); } catch (requestError) { setError(requestError.response?.data?.message || 'Không thể tải hợp đồng.'); } finally { setLoading(false); } }, [route.params.contractId]);
  useEffect(() => { load(); }, [load]);
  const handleConfirm = async () => { setConfirming(true); try { setContract(await confirmContract(contract.id)); Alert.alert('Thành công', 'Bạn đã xác nhận hợp đồng.'); } catch (requestError) { Alert.alert('Không thể xác nhận', requestError.response?.data?.message || 'Vui lòng thử lại sau.'); } finally { setConfirming(false); } };
  if (loading || !contract) return <SafeAreaView style={styles.safe}><View style={styles.top}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="chevron-back" size={25} color={COLORS.text} /></TouchableOpacity><Text style={styles.topTitle}>Chi tiết hợp đồng</Text><View style={styles.spacer} /></View><View style={styles.center}><Text style={styles.loading}>{error || 'Đang tải...'}</Text></View></SafeAreaView>;
  const canConfirm = String(contract.status).toUpperCase() === 'APPROVED'; const imageUrl = contract.images?.[0]?.url;
  return <SafeAreaView style={styles.safe} edges={['top']}><View style={styles.screen}><View style={styles.top}><TouchableOpacity onPress={() => navigation.goBack()}><Ionicons name="chevron-back" size={25} color={COLORS.text} /></TouchableOpacity><Text style={styles.topTitle}>Chi tiết hợp đồng</Text><View style={styles.spacer} /></View><ScrollView contentContainerStyle={[styles.content, canConfirm && styles.withButton]} showsVerticalScrollIndicator={false}><View style={[styles.hero, SHADOW]}>{imageUrl ? <Image source={{ uri: imageUrl }} style={styles.image} resizeMode="cover" /> : <Ionicons name="car-sport-outline" size={64} color={COLORS.muted} />}</View><View style={styles.heading}><View style={styles.headingText}><Text style={styles.code}>{contract.contract_number}</Text><Text style={styles.vehicle}>{contract.brand} {contract.model}</Text></View><StatusBadge status={contract.status} /></View><Text style={styles.price}>{formatVND(contract.total_amount || contract.vehicle_price)}</Text><View style={styles.card}><Text style={styles.sectionTitle}>Thông tin hợp đồng</Text><Row label="Mã hợp đồng" value={contract.contract_number} /><Row label="Xe" value={`${contract.brand || ''} ${contract.model || ''}`.trim()} /><Row label="Khách hàng" value={contract.customer_name} /><Row label="Email" value={contract.customer_email} /><Row label="Ngày tạo" value={contract.created_at ? new Date(contract.created_at).toLocaleDateString('vi-VN') : '—'} /></View><View style={styles.card}><Text style={styles.sectionTitle}>Điều khoản</Text><Text style={styles.terms}>{contract.terms || 'Chưa có điều khoản hợp đồng.'}</Text></View></ScrollView>{canConfirm && <View style={styles.footer}><PrimaryButton title="Xác nhận hợp đồng" onPress={handleConfirm} loading={confirming} /></View>}</View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: COLORS.background }, screen: { flex: 1, backgroundColor: COLORS.background }, top: { height: 58, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: COLORS.border }, topTitle: { color: COLORS.text, fontSize: 16, fontWeight: '900' }, spacer: { width: 25 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, loading: { color: COLORS.muted }, content: { padding: 16, paddingBottom: 28 }, withButton: { paddingBottom: 100 }, hero: { height: 205, borderRadius: 18, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }, image: { width: '100%', height: '100%' }, heading: { flexDirection: 'row', alignItems: 'flex-start', marginTop: 20 }, headingText: { flex: 1, paddingRight: 12 }, code: { color: COLORS.text, fontSize: 20, fontWeight: '900' }, vehicle: { color: COLORS.muted, fontSize: 14, marginTop: 5, textTransform: 'capitalize' }, price: { color: COLORS.price, fontSize: 22, fontWeight: '900', marginTop: 12 }, card: { marginTop: 18, padding: 16, borderRadius: 16, backgroundColor: COLORS.surface, borderWidth: 1, borderColor: COLORS.border }, sectionTitle: { color: COLORS.text, fontSize: 15, fontWeight: '900', marginBottom: 10 }, row: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 9, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: COLORS.border }, rowLabel: { color: COLORS.muted, fontSize: 13 }, rowValue: { color: COLORS.text, fontSize: 13, fontWeight: '700', maxWidth: '62%', textAlign: 'right' }, terms: { color: COLORS.muted, fontSize: 13.5, lineHeight: 21 }, footer: { position: 'absolute', left: 0, right: 0, bottom: 0, padding: 14, paddingBottom: 18, backgroundColor: COLORS.surface, borderTopWidth: 1, borderTopColor: COLORS.border } });
