import { StyleSheet } from "react-native";
import { COLORS } from "../../utils/theme";

export const authStyles = StyleSheet.create({
  background: { flex: 1 },
  overlay: { flex: 1, backgroundColor: "rgba(5,9,18,0.62)" },
  container: { flex: 1 },
  content: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  card: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "rgba(15,23,42,0.32)",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.16)",
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.35,
    shadowRadius: 26,
    elevation: 10,
  },
  brand: { marginBottom: 36 },
  brandTitle: { fontSize: 40, fontWeight: "700", color: COLORS.white },
  brandSub: { fontSize: 14, color: "rgba(255,255,255,0.7)", marginTop: 4 },
  screenTitle: {
    color: COLORS.white,
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 8,
    textAlign: "center",
  },
  screenHint: {
    color: "rgba(226,232,240,0.8)",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 12,
    textAlign: "center",
  },
  label: {
    fontSize: 13,
    color: "rgba(226,232,240,0.9)",
    marginBottom: 8,
    marginTop: 16,
  },
  input: {
    backgroundColor: "rgba(255,255,255,0.10)",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: COLORS.white,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.22)",
  },
  inputError: { borderColor: "#E8776B" },
  fieldError: { color: "#FF9F94", fontSize: 12, marginTop: 6 },
  error: { color: "#FF9F94", fontSize: 13, marginTop: 16 },
  button: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 28,
  },
  buttonDisabled: { opacity: 0.6 },
  buttonText: { color: COLORS.white, fontSize: 15, fontWeight: "700" },
  bottomRow: { flexDirection: "row", justifyContent: "center", marginTop: 24 },
  bottomText: { color: "rgba(226,232,240,0.75)", fontSize: 13 },
  bottomLink: { color: "#93C5FD", fontSize: 13, fontWeight: "700" },
});
